version: '3.8'

name: who-won-that
services: 

  fastapi:
    image: who-won-that_fastapi
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${API_LOCAL_PORT:-8000}:8000
    networks:
      - compose-network

  react:
    image: who-won-that_react
    depends_on:
      - fastapi
    restart: unless-stopped
    env_file: ./.env
    build:
      context: ./frontend
      args:
        - VITE_APP_BACKEND=${VITE_APP_BACKEND:-http://localhost:8000}
    ports:
      - ${FRONTEND_LOCAL_PORT:-80}:80
    networks:
      - compose-network
    volumes:
      - ${NGINX_CONF_PATH:-./nginxDefault/conf/}:/etc/nginx/conf.d/:ro
      - ${NGINX_CERT_PATH:-./nginxDefault/certs/}:/certs/:ro

networks:
  compose-network:
